# speednik/constants.py — All physics constants from specification §2.1–2.4, §3.2

# Screen (§1)
SCREEN_WIDTH = 256
SCREEN_HEIGHT = 224
FPS = 60

# Ground movement (§2.1)
ACCELERATION = 0.046875
DECELERATION = 0.5
FRICTION = 0.046875
TOP_SPEED = 6.0
ROLLING_FRICTION = 0.0234375
ROLLING_DECELERATION = 0.125
MIN_ROLL_SPEED = 0.5
MAX_X_SPEED = 16.0

# Air movement (§2.2)
GRAVITY = 0.21875
JUMP_FORCE = 6.5
AIR_ACCELERATION = 0.09375
JUMP_RELEASE_CAP = -4.0

# Slopes (§2.3)
SLOPE_FACTOR_RUNNING = 0.125
SLOPE_FACTOR_ROLL_UP = 0.078125
SLOPE_FACTOR_ROLL_DOWN = 0.3125

# Spindash (§2.4)
SPINDASH_CHARGE_INCREMENT = 2.0
SPINDASH_MAX_CHARGE = 8.0
SPINDASH_DECAY_DIVISOR = 32.0
SPINDASH_BASE_SPEED = 8.0

# Sensors (§3.2)
STANDING_WIDTH_RADIUS = 9
STANDING_HEIGHT_RADIUS = 20
ROLLING_WIDTH_RADIUS = 7
ROLLING_HEIGHT_RADIUS = 14
WALL_SENSOR_EXTENT = 10

# Slip (§2.3)
SLIP_SPEED_THRESHOLD = 2.5
SLIP_DURATION = 30
# 46° in byte angle: 46 * 256 / 360 ≈ 32.7 → 33
SLIP_ANGLE_THRESHOLD = 33

# Player damage (§8)
INVULNERABILITY_DURATION = 120  # 2 seconds at 60fps
MAX_SCATTER_RINGS = 32
SCATTER_RING_LIFETIME = 180  # 3 seconds at 60fps
HURT_KNOCKBACK_X = 2.0
HURT_KNOCKBACK_Y = -4.0
RING_COLLECTION_RADIUS = 16
EXTRA_LIFE_THRESHOLD = 100

# Springs (§5.4, §7)
SPRING_UP_VELOCITY = -10.0
SPRING_RIGHT_VELOCITY = 10.0
SPRING_HITBOX_W = 16
SPRING_HITBOX_H = 16
SPRING_COOLDOWN_FRAMES = 8

# Checkpoints (§8)
CHECKPOINT_ACTIVATION_RADIUS = 20

# Launch pipes (§7.2)
PIPE_ENTRY_HITBOX_W = 24
PIPE_ENTRY_HITBOX_H = 24

# Liquid rise (§7.2)
LIQUID_RISE_SPEED = 1.0

# Enemies (§5.3, §7.1–7.3)
ENEMY_BOUNCE_VELOCITY = -6.5
CRAB_PATROL_SPEED = 0.5
CRAB_PATROL_RANGE = 32  # ±32px from origin = 64px total
CHOPPER_JUMP_INTERVAL = 90
CHOPPER_JUMP_VELOCITY = -5.0
SPINDASH_KILL_THRESHOLD = 8.0

# Enemy hitboxes
CRAB_HITBOX_W = 16
CRAB_HITBOX_H = 14
BUZZER_HITBOX_W = 12
BUZZER_HITBOX_H = 12
CHOPPER_HITBOX_W = 8
CHOPPER_HITBOX_H = 16
GUARDIAN_HITBOX_W = 24
GUARDIAN_HITBOX_H = 28

# Boss: Egg Piston (§7.3)
BOSS_HP = 8
BOSS_ESCALATION_HP = 4             # HP at which escalation triggers
BOSS_IDLE_DURATION = 120           # 2.0s at 60fps
BOSS_DESCEND_DURATION = 60         # 1.0s
BOSS_VULNERABLE_DURATION = 90      # 1.5s
BOSS_VULNERABLE_DURATION_ESC = 60  # 1.0s after escalation
BOSS_ASCEND_DURATION = 60          # 1.0s
BOSS_IDLE_SPEED = 1.0              # px/frame
BOSS_IDLE_SPEED_ESC = 2.0          # px/frame after escalation
BOSS_INDICATOR_LEAD = 60           # frames before descend when indicator appears
BOSS_HITBOX_W = 24
BOSS_HITBOX_H = 32
BOSS_HIT_INVULN = 30              # frames of boss invulnerability after hit
BOSS_ARENA_HALF_W = 128           # ±128px from spawn for patrol bounds

# Goal / Game state (§1, §8)
GOAL_ACTIVATION_RADIUS = 24
DEATH_DELAY_FRAMES = 120        # 2 seconds at 60fps
RESULTS_DURATION = 300           # 5 seconds at 60fps
GAMEOVER_DELAY = 360             # 6 seconds — jingle + pause
BOSS_ARENA_START_X = 4000       # x threshold for boss music in Stage 3
BOSS_SPAWN_X = 4800.0           # Boss spawn x for Stage 3
BOSS_SPAWN_Y = 480.0            # Boss ground level for Stage 3

# Angle system
ANGLE_STEPS = 256

# Camera horizontal
CAMERA_LEFT_BORDER = 144
CAMERA_RIGHT_BORDER = 160
CAMERA_H_SCROLL_CAP = 16

# Camera vertical
CAMERA_FOCAL_Y = 96
CAMERA_AIR_BORDER = 32
CAMERA_V_SCROLL_GROUND_SLOW = 6
CAMERA_V_SCROLL_GROUND_FAST = 16
CAMERA_V_SCROLL_AIR = 16
CAMERA_GROUND_SPEED_THRESHOLD = 8.0

# Camera look
CAMERA_LOOK_UP_MAX = 104
CAMERA_LOOK_DOWN_MAX = 88
CAMERA_LOOK_SPEED = 2
